filtros/urls.py
from django.urls import path

from . import views

app_name = 'filtros'
urlpatterns = [
	path('', views.index, name='index'),
	path('send/', views.send, name='send'),
]

proj/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('filtros.urls', namespace='filtros')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filtros/models.py
from django.db import models

class Foto(models.Model):
	titulo = models.CharField(max_length=50)
	url = models.CharField(max_length=255)
	ready = models.BooleanField(default=False)

filtros/forms.py
from django import forms

class UploadFileForm(forms.Form):
    titulo = forms.CharField(max_length=50)
    foto  = forms.FileField()

filtros/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from filtros.forms import UploadFileForm
from filtros.tasks import apply_filter
from filtros.models import Foto
from utils import fileutils


def index(request):
	context = {
		'form': UploadFileForm(),
		'fotos': Foto.objects.all(),
	}
	return render(request, 'index.html', context)


def send(request):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			filepath = fileutils.upload_file(request.FILES['foto'])
			foto = Foto.objects.create(titulo=form.cleaned_data['titulo'], url=filepath)
			apply_filter.delay(filepath, foto.id)
			return HttpResponseRedirect(reverse('filtros:index'))
	else:
		form = UploadFileForm()

	context = {
		'form': form,
		'fotos': Foto.objects.all(),
	}
	return render(request, 'index.html', context)

filtros/templates/index.html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<title>Filtros</title>
	<style>
		.foto {
			display: inline-block;
			width: 100px;
		}
	</style>
</head>
<body>
	<section id="fotoform">
		<h4>Sube tu foto</h4>
		<form action="{% url 'filtros:send' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Enviar" />
		</form>
	</section>
	<section id="fotolist">
		{% for foto in fotos %}
			<div class="foto">
				<h5>{{ foto.titulo }}</h5>
				{% if not foto.ready %}
					<p>Foto cargandose</p>
				{% else %}
					<img src="{{ foto.url }}" style='max-height: 100px; max-width: 100px' />
				{% endif %}
			</div>
		{% endfor %}
	</section>
</body>
</html>